### PR TITLE
feat: Windows fast launch

### LINKED ISSUE #466: feat: windows runner - enable fast launch option
Currently it takes up to 4 minutes to get a windows runner up and running and registered in GH.
AWS announced this last year... 
https://aws.amazon.com/blogs/modernizing-with-aws/launch-windows-faster-on-ec2/

This can be configured in distribution settings in image builder
https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/win-ami-config-fast-launch.html#win-fast-launch-key-terms

Important is that if no fast launch snapshots are available the standard launch will be done...

```
When you experience a higher number of launches than anticipated, you might use up all the pre-provisioned snapshots that you have available. This doesn't cause any launches to fail. However, it can result in some instances going through the standard launch process, until snapshots can be replenished.
```

Could we implement this stuff @kichik  ?
I could create a first draft PR ...
What`s your opinion on this ?

### PR DESCRIPTION
**Pull request by kichik**
Add an option for enabling [fast launch](https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/win-ami-config-fast-launch.html) for Windows AMIs. This should speed up booting up of EC2 Windows runners.

Note that it does come with [extra cost](https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/win-fast-launch-manage-costs.html).

```typescript
const ec2WindowsImageBuilder = Ec2RunnerProvider.imageBuilder(stack, 'Windows EC2 Builder', {
  os: Os.WINDOWS,
  vpc,
  awsImageBuilderOptions: {
    fastLaunchOptions: {
      enabled: true,
    },
  },
});
const runners = new GitHubRunners(stack, 'runners', {
  providers: [
    new Ec2RunnerProvider(stack, 'Fast Windows', {
      labels: ['windows'],
      imageBuilder: ec2WindowsImageBuilder,
    }),
  ],
}
```

Before:
image

After:
image

Resolves #466
Closes #514

### CODE REVIEW

**Comment by pharindoko** [comment]
Tried it out: Works super easy and great.
Only thing I have found - It had listed 6 subnets in the stepfunctions while I only provided 2.

image

**Comment by kichik** [comment]
Thanks! Not sure how the subnets can change as nothing was modified on the provider side. Would you mind sharing the code that limits to two subnets?

**Comment by pharindoko** [comment]
will check this next week and try it out in another account as well.

**Comment by pharindoko** [comment]
@kichik As promised I tried it out in another account with non-default vpc and it works as well in a super nice way. Haven`t seen any issues yet :) - so here`s my approval :D

**Comment by kichik** [comment]
Thanks @pharindoko!

**Pull request merged**
