### PR TITLE
feat: Allow custom `LambdaAccess` implmentations

### LINKED ISSUE #324: feat: set custom domain name for apigatewayaccess
Hey @kichik,

I currently test the option to use the LambdaAccess.apiGateway option 

```typescript
 new GitHubRunners(this, `${this.stackName}-github-runner`, {
      providers: [githubRunner],
      vpc: existingVpc,
      vpcSubnets: vpcSubnets,
      logOptions: {
        includeExecutionData: true,
        level: stepfunctions.LogLevel.ALL,
        logGroupName: `${this.stackName}-state-machine`,
      },
      allowPublicSubnet: false,
      webhookAccess: LambdaAccess.apiGateway({
        allowedVpcEndpoints: [vpcEndpoint],
      }),
      setupAccess: LambdaAccess.apiGateway({
        allowedVpcEndpoints: [vpcEndpoint],
      }),
      statusAccess: LambdaAccess.apiGateway({
        allowedVpcEndpoints: [vpcEndpoint],
      }),
    });
```
 
In our setup I cannot use the {vpce-id}-{rest-api}.amazon url style as webhook url. I need to use a custom domain name. (I know the root cause ...)

**What I would like to have:**

I need the additional option to set a custom domain name when the apigateway access is used.
https://github.com/CloudSnorkel/cdk-github-runners/blob/89ba369976f63dd7e937ddfc4e540efa04434a23/src/access.ts#L236

e.g. a optional property called customDomains (stringArray) that I can pass into the apiGateway function.

```typescript
 new GitHubRunners(this, `${this.stackName}-github-runner`, {
      providers: [githubRunner],
      vpc: existingVpc,
      vpcSubnets: vpcSubnets,
      logOptions: {
        includeExecutionData: true,
        level: stepfunctions.LogLevel.ALL,
        logGroupName: `${this.stackName}-state-machine`,
      },
      allowPublicSubnet: false,
      webhookAccess: LambdaAccess.apiGateway({
        allowedVpcEndpoints: [vpcEndpoint],
        customDomain: xxx.domain.com
      }),
      setupAccess: LambdaAccess.apiGateway({
        allowedVpcEndpoints: [vpcEndpoint],
      }),
      statusAccess: LambdaAccess.apiGateway({
        allowedVpcEndpoints: [vpcEndpoint],
      }),
    });
```

In the background:
- custom domains will be created
- add a basepathMapping for each custom domain to map the custom domain to the created apigateway.RestApi

**Alternative:**
Add the ability to overwrite the webhook url and return the apigateway as property.
Then I could create the custom domain name and create the api gateway binding on my own.

### PR DESCRIPTION
**Pull request by kichik**
Expose `LambdaAccess.bind()` so users can implement their own access to webhooks. This can be used to setup a custom domain, for example.

```typescript
class CustomDomainLambdaAccess extends LambdaAccess {
  bind(scope: Construct, id: string, lambdaFunction: lambda.Function): string {
    const api = new apigateway.LambdaRestApi(scope, id, {
      handler: lambdaFunction,
      proxy: true,
      cloudWatchRole: false,
      domainName: {
        domainName: 'webhook.my-custom-domain.com',
        certificate: acm.Certificate.fromCertificateArn(scope, 'cert', 'arn:aws:acm:us-east-1:123456789012:certificate/12345678-1234-1234-1234-123456789012'),
      },
      policy: PolicyDocument.fromJson({
        Version: '2012-10-17',
        Statement: [
          {
            Effect: 'Allow',
            Principal: '*',
            Action: 'execute-api:Invoke',
            Resource: 'execute-api:/*/*/*',
            Condition: {
              IpAddress: {
                'aws:SourceIp': ['1.2.3.4/32'],
              },
            },
          },
        ],
      }),
    });

    new route53.CnameRecord(scope, 'cname', {
      domainName: `${api.restApiId}.execute-api.us-east-1.amazonaws.com`,
      recordName: 'webhook',
      zone: route53.HostedZone.fromHostedZoneId(scope, 'hosted-zone', 'Z1234567890'),
    });

    return 'https://webhook.my-custom-domain.com/prod';
  }
}

new GitHubRunners(this, 'runners', {
  webhookAccess: new CustomDomainLambdaAccess(),
});
```

Closes #324

### CODE REVIEW

**Comment by quad** [comment]
We actually wrote the following in-house:

```javascript
class IAMAccess extends LambdaAccess {
    constructor(readonly grantee: IGrantable) {
        super();
    }

    _bind(_construct: Construct, _id: string, lambdaFunction: Function): string {
        let url = lambdaFunction.addFunctionUrl({
            authType: FunctionUrlAuthType.AWS_IAM,
        });
        url.grantInvokeUrl(this.grantee);

        return url.url;
    }
}

new GitHubRunners(this, "runners", {
    setupAccess: new IAMAccess(role_admin),
    statusAccess: new IAMAccess(role_read_only),
    ...
});
```

**Comment by kichik** [comment]
Since `_bind()` is internal and not meant to be used, that will not work in any other language. This Python code will not work as expected:

```
import aws_cdk as cdk
from cloudsnorkel.cdk_github_runners import GitHubRunners, LambdaAccess
import os


class InternalBind(LambdaAccess):
    def __init__(self):
        super().__init__()

    def _bind(self, scope, id_, func):
        raise RuntimeError('never going to get called')

app = cdk.App()
stack = cdk.Stack(app, 'stack', env={"account": os.environ['CDK_DEFAULT_ACCOUNT'], "region": os.environ['CDK_DEFAULT_REGION']})
GitHubRunners(stack, 'runners', webhook_access=InternalBind())

app.synth()
```

It fails with:

```
RuntimeError: access._bind is not a function
```

**Comment by pharindoko** [comment]
@kichik 
Ok I got this working now with my private api gateway + custom domain solution.

setup url: runner.example.com/?token=xxxxxx
webhook url: runner.example.com/webhook

When I attach an existing app it works perfectly.
When I create a new app and it redirects back to route /complete-new-app, it fails.

My issue is this line that appends a stage to the github redirect url and in my case to the custom domain.

https://github.com/CloudSnorkel/cdk-github-runners/blob/4c4e2541b9e0b43ffed6e205e90c5f7fa7c76d44/src/setup.lambda.ts#L36

Do you have any idea how we could ignore custom domains ? 
One approach would be to add a condition to detect if amazon.com is included ...

**Comment by kichik** [comment]
> Do you have any idea how we could ignore custom domains ?

We might be able to find another parameter in both types of context to give us the full path including the stage so it works for both API Gateway and Lambda URL.

**Comment by pharindoko** [comment]
domainname + rawPath / http.path should work as combination...

**Comment by kichik** [comment]
We would need to make it works with Lambda URL, public API Gateway, private API Gateway, and API Gateway with domain.

**Comment by pharindoko** [comment]
> We would need to make it works with Lambda URL, public API Gateway, private API Gateway, and API Gateway with domain.

Hmm I assume that the event object ApiGatewayEvent is the same at least for the public/private ApiGateway with or without custom domain.
Don't know how it is for the Lambda Function url... guess I need to test it.

**Comment by pharindoko** [comment]
> It's similar but slightly different. It's basically this line.
> 
> 
> 
> https://github.com/CloudSnorkel/cdk-github-runners/blob/4c4e2541b9e0b43ffed6e205e90c5f7fa7c76d44/src/setup.lambda.ts#L8

Ah seems like I ignored this line, sorry.
I'll try to figure this out next week.

**Pull request merged**
