### PR TITLE
feat: Allow full customization of runner images and periodically update them

### LINKED ISSUE #7: More runner architectures
Windows, ARM, GPU, and maybe even Mac once we get EC2 instance support.

### LINKED ISSUE #26: Runner image customization
User should be able to install additional dependencies, setup internal repositories, and in general fully customize the image to their needs.

### PR DESCRIPTION
**Pull request by kichik**
Build images in AWS using CodeBuild (or any user configured method) so that:
1. We can automatically update images on a schedule to get the latest runner version and latest OS updates.
2. We can build any type of image independent of the deployment platform. This will make it easy to provide Windows or ARM images (closes #7).
3. We can expose an interface allowing the user to easily modify the Docker images by adding packages or commands to the build process (closes #26).

BREAKING CHANGE: providers no longer take runner version directly

### CODE REVIEW

**Comment by kichik** [comment]
See the [updated readme](https://github.com/CloudSnorkel/cdk-github-runners/blob/e59402855d1a4e9591f43242b19a055c88a3b7cb/README.md) for usage.

**Comment by sercantor** [comment]
Would it be more obvious to have a matching provider label for `self-hosted.yml` and the readme? Like:

```typescript
// create a custom CodeBuild provider
const myProvider = new CodeBuildRunner(this, 'codebuild runner', { 
    label: 'codebuild-x64',
    ...
});
// grant some permissions to the provider
...

// create the runner infrastructure
new GitHubRunners(this, 'runners', {
    providers: [codebuild-x64],
});
```

I'm just suggesting it because there may be people copying from the readme and not seeing their workers running because the labels don't match when they run their workflow against `self.hosted.yml`. Also makes it obvious for people to see that there are options for architecture.

Again, it's just a suggestion 🤷

**Comment by kichik** [comment]
That's a good point. I keep forgetting to add proper workflow example. `self-hosted.yml` is not an ideal example. It's way too complex.

**Comment by sercantor** [comment]
great commit, it's definitely more readable now, thanks for all the work 👍

**Pull request merged**
